### PR TITLE
Jw ticket#1

### PR DESCRIPTION
**Pull request by johnnathanwood**
## Link to Ticket
Closes # 1/2 for ticket #11 

## Description of Proposed Changes

- Added sell product to nav bar. Will only appear if user is authenticated. When user clicks on sell product, they are redirected to sell product form

## Steps to Test

Pull down branch jw-ticket#1

```sh
git fetch --all
git checkout jw-ticket#1
```

## Impacted Areas in Application

List general components of the application that this PR will affect:

* .views/__init__.py 
* navbar.html

### CODE REVIEW

**Comment by CosignMyCodesign** [comment]
👍 looks good

**Comment by robbyhecht** [comment]
👍 Totes works brah
Check out the pull request instructions for next time so i can see what I should be testing 😜

**Review by robbyhecht — APPROVED** [review]
👍 Totes works brah
Check out the pull request instructions for next time so i can see what I should be testing 😜

**Review by danielreedcombs — APPROVED** [review]
👍

**Review by CosignMyCodesign — APPROVED** [review]

**Pull request merged**
